package help.me.orm.entity;
// Generated Nov 26, 2015 6:04:16 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Info generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "info")
public class Info implements java.io.Serializable {

	private int infoId;
	private User user;
	private String address;
	private String city;
	private String zipcode;
	private String phoneNumber;
	private boolean phoneOk;
	private boolean textOk;
	private boolean emailOk;
	private Date createdAt;
	private Date updatedAt;

	public Info() {
	}

	/**
	 * @param infoId
	 * @param user
	 * @param address
	 * @param city
	 * @param zipcode
	 * @param phoneNumber
	 * @param phoneOk
	 * @param textOk
	 * @param emailOk
	 */
	public Info(int infoId, User user, String address, String city, String zipcode, String phoneNumber, boolean phoneOk,
			boolean textOk, boolean emailOk) {
		this.infoId = infoId;
		this.user = user;
		this.address = address;
		this.city = city;
		this.zipcode = zipcode;
		this.phoneNumber = phoneNumber;
		this.phoneOk = phoneOk;
		this.textOk = textOk;
		this.emailOk = emailOk;
	}

	/**
	 * @param infoId
	 * @param user
	 * @param address
	 * @param city
	 * @param zipcode
	 * @param phoneNumber
	 * @param phoneOk
	 * @param textOk
	 * @param emailOk
	 * @param createdAt
	 * @param updatedAt
	 */
	public Info(int infoId, User user, String address, String city, String zipcode, String phoneNumber, boolean phoneOk,
			boolean textOk, boolean emailOk, Date createdAt, Date updatedAt) {
		this.infoId = infoId;
		this.user = user;
		this.address = address;
		this.city = city;
		this.zipcode = zipcode;
		this.phoneNumber = phoneNumber;
		this.phoneOk = phoneOk;
		this.textOk = textOk;
		this.emailOk = emailOk;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@Column(name = "infoId", unique = true, nullable = false)
	public int getInfoId() {
		return this.infoId;
	}

	public void setInfoId(int infoId) {
		this.infoId = infoId;
	}

	@Column(name = "user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "address", nullable = false, length = 64)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city", nullable = false, length = 64)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "zipcode", nullable = false, length = 5)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "phoneNumber", nullable = false, length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "phoneOk", nullable = false)
	public boolean isPhoneOk() {
		return this.phoneOk;
	}

	public void setPhoneOk(boolean phoneOk) {
		this.phoneOk = phoneOk;
	}

	@Column(name = "textOk", nullable = false)
	public boolean isTextOk() {
		return this.textOk;
	}

	public void setTextOk(boolean textOk) {
		this.textOk = textOk;
	}

	@Column(name = "emailOk", nullable = false)
	public boolean isEmailOk() {
		return this.emailOk;
	}

	public void setEmailOk(boolean emailOk) {
		this.emailOk = emailOk;
	}

	@Generated(GenerationTime.INSERT) 
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19, insertable=false, updatable=false)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Generated(GenerationTime.ALWAYS) 
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19, insertable=false, updatable=true)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}


}
