package help.me.orm.entity;
// Generated Nov 26, 2015 6:04:16 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * License generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "license",  uniqueConstraints = @UniqueConstraint(columnNames = "licenseNumber") )
public class License implements java.io.Serializable {

	private int licenseId;
	private User user;
	private String licenseNumber;
	private Service service;
	private Date createdAt;
	private Date updatedAt;

	public License() {
	}

	public License(int licenseId, User user, String licenseNumber, Service service) {
		this.licenseId = licenseId;
		this.user = user;
		this.licenseNumber = licenseNumber;
		this.service = service;
	}

	public License(int licenseId, User user, String licenseNumber, Service service, Date createdAt, Date updatedAt) {
		this.licenseId = licenseId;
		this.user = user;
		this.licenseNumber = licenseNumber;
		this.service = service;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "licenseId", unique = true, nullable = false)
	public int getLicenseId() {
		return this.licenseId;
	}

	public void setLicenseId(int licenseId) {
		this.licenseId = licenseId;
	}

	@Column(name = "user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "licenseNumber", unique = true, nullable = false, length = 32)
	public String getLicenseNumber() {
		return this.licenseNumber;
	}

	public void setLicenseNumber(String licenseNumber) {
		this.licenseNumber = licenseNumber;
	}

	@Column(name = "service", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@Generated(GenerationTime.INSERT) 
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19, insertable=false, updatable=false)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Generated(GenerationTime.ALWAYS) 
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19, insertable=false, updatable=true)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}


}
