package help.me.orm.entity;
// Generated Nov 26, 2015 3:23:57 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * License generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "license", uniqueConstraints = @UniqueConstraint(columnNames = "licenseNumber") )
public class License implements java.io.Serializable {

	private Integer licenseId;
	private Service service;
	private User user;
	private String licenseNumber;
	private Date createdAt;
	private Date updatedAt;

	public License() {
	}

	public License(Service service, User user, String licenseNumber) {
		this.service = service;
		this.user = user;
		this.licenseNumber = licenseNumber;
	}

	public License(Service service, User user, String licenseNumber, Date createdAt, Date updatedAt) {
		this.service = service;
		this.user = user;
		this.licenseNumber = licenseNumber;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "licenseId", unique = true, nullable = false)
	public Integer getLicenseId() {
		return this.licenseId;
	}

	public void setLicenseId(Integer licenseId) {
		this.licenseId = licenseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "licenseNumber", unique = true, nullable = false, length = 32)
	public String getLicenseNumber() {
		return this.licenseNumber;
	}

	public void setLicenseNumber(String licenseNumber) {
		this.licenseNumber = licenseNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
