package help.me.orm.entity;
// Generated Nov 26, 2015 6:04:16 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.search.annotations.Field;

/**
 * Service generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "service", uniqueConstraints = {
		@UniqueConstraint(columnNames = "serviceName"),
		@UniqueConstraint(columnNames = "longDescription")
})
public class Service implements java.io.Serializable {
	private int serviceId;

	@Field
	private String serviceName;
	private String longDescription;
	private String iconFileName;
	
	public Service() {}
	
	/**
	 * Jackson constructor.
	 * 
	 * @param serviceName
	 */
	public Service(String serviceName, String longDescription) {
		this(-1, serviceName, longDescription, null);
	}

	/**
	 * @param serviceId
	 * @param serviceName
	 * @param longDescription
	 * @param iconFileName
	 */
	public Service(int serviceId, String serviceName, String longDescription, String iconFileName) {
		this.serviceId = serviceId;
		this.serviceName = serviceName;
		this.longDescription = longDescription;
		this.iconFileName = iconFileName;
	}

	@Id
	@GeneratedValue(generator="serviceIncrement")
	@GenericGenerator(name="serviceIncrement", strategy = "increment")
	@Column(name = "serviceId", unique = true, nullable = false)
	public int getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "serviceName", unique = true, nullable = false, length = 100)
	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String description) {
		this.serviceName = description;
	}

	@Column(name = "longDescription", unique = true, nullable = false)
	public String getLongDescription() {
		return this.longDescription;
	}

	public void setLongDescription(String longDescription) {
		this.longDescription = longDescription;
	}

	@Column(name = "iconFileName", unique = false, nullable = false, length = 100)
	public String getIconFileName() {
		return this.iconFileName;
	}
	
	public void setIconFileName(String iconFileName) {
		this.iconFileName = iconFileName;
	}
	
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Service [serviceId=");
		builder.append(serviceId);
		builder.append(", serviceName=");
		builder.append(serviceName);
		builder.append(", longDescription=");
		builder.append(longDescription);
		builder.append(", iconFileName=");
		builder.append(iconFileName);
		builder.append("]");
		return builder.toString();
	}

}
