package help.me.orm.entity;
// Generated Nov 26, 2015 6:04:16 PM by Hibernate Tools 4.3.1.Final

import java.sql.Time;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;
import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Settings generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "settings")
public class Settings implements java.io.Serializable {
	
	@JsonIgnore
	private int settingsId;
	@JsonIgnore
	private User user;
	@JsonIgnore
	private Date createdAt;
	@JsonIgnore
	private Date updatedAt;

	@JsonProperty("mondayStart")
	private Time mondayStart;
	@JsonProperty("mondayEnd")
	private Time mondayEnd;
	@JsonProperty("tuesdayStart")
	private Time tuesdayStart;
	@JsonProperty("tuesdayEnd")
	private Time tuesdayEnd;
	@JsonProperty("wednesdayStart")
	private Time wednesdayStart;
	@JsonProperty("wednesdayEnd")
	private Time wednesdayEnd;
	@JsonProperty("thursdayStart")
	private Time thursdayStart;
	@JsonProperty("thursdayEnd")
	private Time thursdayEnd;
	@JsonProperty("fridayStart")
	private Time fridayStart;
	@JsonProperty("fridayEnd")
	private Time fridayEnd;
	@JsonProperty("saturdayStart")
	private Time saturdayStart;
	@JsonProperty("saturdayEnd")
	private Time saturdayEnd;
	@JsonProperty("sundayStart")
	private Time sundayStart;
	@JsonProperty("sundayEnd")
	private Time sundayEnd;

	public Settings() {
	}

	public Settings(int settingsId, User user) {
		this.settingsId = settingsId;
		this.user = user;
	}

	public Settings(int settingsId, Time mondayStart, Time mondayEnd, Time tuesdayStart, Time tuesdayEnd,
			Time wednesdayStart, Time wednesdayEnd, Time thursdayStart, Time thursdayEnd, Time fridayStart,
			Time fridayEnd, Time saturdayStart, Time saturdayEnd, Time sundayStart, Time sundayEnd, User user) {
		this.settingsId = settingsId;
		this.mondayStart = mondayStart;
		this.mondayEnd = mondayEnd;
		this.tuesdayStart = tuesdayStart;
		this.tuesdayEnd = tuesdayEnd;
		this.wednesdayStart = wednesdayStart;
		this.wednesdayEnd = wednesdayEnd;
		this.thursdayStart = thursdayStart;
		this.thursdayEnd = thursdayEnd;
		this.fridayStart = fridayStart;
		this.fridayEnd = fridayEnd;
		this.saturdayStart = saturdayStart;
		this.saturdayEnd = saturdayEnd;
		this.sundayStart = sundayStart;
		this.sundayEnd = sundayEnd;
		this.user = user;
	}

	
	@Id
	@GeneratedValue(generator="settingsIncrement")
	@GenericGenerator(name="settingsIncrement", strategy = "increment")
	@Column(name = "settingsId", unique = true, nullable = false)
	public int getSettingsId() {
		return this.settingsId;
	}

	public void setSettingsId(int settingsId) {
		this.settingsId = settingsId;
	}

	@Column(name = "mondayStart", length = 8)
	public Time getMondayStart() {
		return this.mondayStart;
	}

	public void setMondayStart(Time mondayStart) {
		this.mondayStart = mondayStart;
	}

	@Column(name = "mondayEnd", length = 8)
	public Time getMondayEnd() {
		return this.mondayEnd;
	}

	public void setMondayEnd(Time mondayEnd) {
		this.mondayEnd = mondayEnd;
	}

	@Column(name = "tuesdayStart", length = 8)
	public Time getTuesdayStart() {
		return this.tuesdayStart;
	}

	public void setTuesdayStart(Time tuesdayStart) {
		this.tuesdayStart = tuesdayStart;
	}

	@Column(name = "tuesdayEnd", length = 8)
	public Time getTuesdayEnd() {
		return this.tuesdayEnd;
	}

	public void setTuesdayEnd(Time tuesdayEnd) {
		this.tuesdayEnd = tuesdayEnd;
	}

	@Column(name = "wednesdayStart", length = 8)
	public Time getWednesdayStart() {
		return this.wednesdayStart;
	}

	public void setWednesdayStart(Time wednesdayStart) {
		this.wednesdayStart = wednesdayStart;
	}

	@Column(name = "wednesdayEnd", length = 8)
	public Time getWednesdayEnd() {
		return this.wednesdayEnd;
	}

	public void setWednesdayEnd(Time wednesdayEnd) {
		this.wednesdayEnd = wednesdayEnd;
	}

	@Column(name = "thursdayStart", length = 8)
	public Time getThursdayStart() {
		return this.thursdayStart;
	}

	public void setThursdayStart(Time thursdayStart) {
		this.thursdayStart = thursdayStart;
	}

	@Column(name = "thursdayEnd", length = 8)
	public Time getThursdayEnd() {
		return this.thursdayEnd;
	}

	public void setThursdayEnd(Time thursdayEnd) {
		this.thursdayEnd = thursdayEnd;
	}

	@Column(name = "fridayStart", length = 8)
	public Time getFridayStart() {
		return this.fridayStart;
	}

	public void setFridayStart(Time fridayStart) {
		this.fridayStart = fridayStart;
	}

	@Column(name = "fridayEnd", length = 8)
	public Time getFridayEnd() {
		return this.fridayEnd;
	}

	public void setFridayEnd(Time fridayEnd) {
		this.fridayEnd = fridayEnd;
	}

	@Column(name = "saturdayStart", length = 8)
	public Time getSaturdayStart() {
		return this.saturdayStart;
	}

	public void setSaturdayStart(Time saturdayStart) {
		this.saturdayStart = saturdayStart;
	}

	@Column(name = "saturdayEnd", length = 8)
	public Time getSaturdayEnd() {
		return this.saturdayEnd;
	}

	public void setSaturdayEnd(Time saturdayEnd) {
		this.saturdayEnd = saturdayEnd;
	}

	@Column(name = "sundayStart", length = 8)
	public Time getSundayStart() {
		return this.sundayStart;
	}

	public void setSundayStart(Time sundayStart) {
		this.sundayStart = sundayStart;
	}

	@Column(name = "sundayEnd", length = 8)
	public Time getSundayEnd() {
		return this.sundayEnd;
	}

	public void setSundayEnd(Time sundayEnd) {
		this.sundayEnd = sundayEnd;
	}

	@JoinColumn(name = "user")
	@OneToOne(fetch=FetchType.LAZY)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Generated(GenerationTime.INSERT) 
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19, insertable=false, updatable=false)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Generated(GenerationTime.ALWAYS) 
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19, insertable=false, updatable=true)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * Used for updating.  This will get all the values from settings that are not null 
	 * and set them in this.  
	 * 
	 * @param settings object to do a "merge" of sorts with this.
	 */
	@Transient
	public void updateValuesFromOther(Settings settings) {
		// No real good way to do this but the long way...balls.
		
		Time t = settings.getMondayStart();
		
		// Monday
		if (t != null) {
			mondayStart = t;
		}
		
		t = settings.getMondayEnd();
		
		if (t != null) {
			mondayEnd = t;
		}
		
		// Tuesday
		t = settings.getTuesdayStart();
		
		if (t != null) {
			tuesdayStart = t;
		}
		
		t = settings.getTuesdayEnd();
		
		if (t != null) {
			tuesdayEnd = t;
		}

		// Wednesday
		t = settings.getWednesdayStart();
		
		if (t != null) {
			wednesdayStart = t;
		}
		
		t = settings.getWednesdayEnd();
		
		if (t != null) {
			wednesdayEnd = t;
		}
		
		// Thursday
		t = settings.getThursdayStart();
		
		if (t != null) {
			thursdayStart = t;
		}
		
		t = settings.getThursdayEnd();
		
		if (t != null) {
			thursdayEnd = t;
		}

		// Friday
		t = settings.getFridayStart();
		
		if (t != null) {
			fridayStart = t;
		}
		
		t = settings.getFridayEnd();
		
		if (t != null) {
			fridayEnd = t;
		}
		
		// Saturday
		t = settings.getSaturdayStart();
		
		if (t != null) {
			saturdayStart = t;
		}
		
		t = settings.getSaturdayEnd();
		
		if (t != null) {
			saturdayEnd = t;
		}

		// Sunday
		t = settings.getSundayStart();
		
		if (t != null) {
			sundayStart = t;
		}
		
		t = settings.getSundayEnd();
		
		if (t != null) {
			sundayEnd = t;
		}
	}
	
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Settings [settingsId=");
		builder.append(settingsId);
		builder.append(", mondayStart=");
		builder.append(mondayStart);
		builder.append(", mondayEnd=");
		builder.append(mondayEnd);
		builder.append(", tuesdayStart=");
		builder.append(tuesdayStart);
		builder.append(", tuesdayEnd=");
		builder.append(tuesdayEnd);
		builder.append(", wednesdayStart=");
		builder.append(wednesdayStart);
		builder.append(", wednesdayEnd=");
		builder.append(wednesdayEnd);
		builder.append(", thursdayStart=");
		builder.append(thursdayStart);
		builder.append(", thursdayEnd=");
		builder.append(thursdayEnd);
		builder.append(", fridayStart=");
		builder.append(fridayStart);
		builder.append(", fridayEnd=");
		builder.append(fridayEnd);
		builder.append(", saturdayStart=");
		builder.append(saturdayStart);
		builder.append(", saturdayEnd=");
		builder.append(saturdayEnd);
		builder.append(", sundayStart=");
		builder.append(sundayStart);
		builder.append(", sundayEnd=");
		builder.append(sundayEnd);
		builder.append(", user=");
		builder.append(user == null ? null : user.getUserId());
		builder.append(", createdAt=");
		builder.append(createdAt);
		builder.append(", updatedAt=");
		builder.append(updatedAt);
		builder.append("]");
		return builder.toString();
	}

}
