package help.me.orm.entity;
// Generated Nov 26, 2015 3:23:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "user", uniqueConstraints = @UniqueConstraint(columnNames = "email") )
public class User implements java.io.Serializable {

	private Integer userId;
	private boolean isProvider;
	private String firstName;
	private String lastName;
	private String suffix;
	private String address;
	private String city;
	private String zipcode;
	private String phoneNumber;
	private boolean phoneOk;
	private boolean textOk;
	private boolean emailOk;
	private Date mondayStart;
	private Date mondayEnd;
	private Date tuesdayStart;
	private Date tuesdayEnd;
	private Date wednesdayStart;
	private Date wednesdayEnd;
	private Date thursdayStart;
	private Date thursdayEnd;
	private Date fridayStart;
	private Date fridayEnd;
	private Date saturdayStart;
	private Date saturdayEnd;
	private Date sundayStart;
	private Date sundayEnd;
	private String email;
	private Date createdAt;
	private Date updatedAt;
	private Set<Location> locations = new HashSet<Location>(0);
	private Set<License> licenses = new HashSet<License>(0);

	public User() {
	}

	public User(boolean isProvider, String firstName, String lastName, String address, String city, String zipcode,
			String phoneNumber, boolean phoneOk, boolean textOk, boolean emailOk, String email) {
		this.isProvider = isProvider;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address = address;
		this.city = city;
		this.zipcode = zipcode;
		this.phoneNumber = phoneNumber;
		this.phoneOk = phoneOk;
		this.textOk = textOk;
		this.emailOk = emailOk;
		this.email = email;
	}

	public User(boolean isProvider, String firstName, String lastName, String suffix, String address, String city,
			String zipcode, String phoneNumber, boolean phoneOk, boolean textOk, boolean emailOk, Date mondayStart,
			Date mondayEnd, Date tuesdayStart, Date tuesdayEnd, Date wednesdayStart, Date wednesdayEnd,
			Date thursdayStart, Date thursdayEnd, Date fridayStart, Date fridayEnd, Date saturdayStart,
			Date saturdayEnd, Date sundayStart, Date sundayEnd, String email, Date createdAt, Date updatedAt,
			Set<Location> locations, Set<License> licenses) {
		this.isProvider = isProvider;
		this.firstName = firstName;
		this.lastName = lastName;
		this.suffix = suffix;
		this.address = address;
		this.city = city;
		this.zipcode = zipcode;
		this.phoneNumber = phoneNumber;
		this.phoneOk = phoneOk;
		this.textOk = textOk;
		this.emailOk = emailOk;
		this.mondayStart = mondayStart;
		this.mondayEnd = mondayEnd;
		this.tuesdayStart = tuesdayStart;
		this.tuesdayEnd = tuesdayEnd;
		this.wednesdayStart = wednesdayStart;
		this.wednesdayEnd = wednesdayEnd;
		this.thursdayStart = thursdayStart;
		this.thursdayEnd = thursdayEnd;
		this.fridayStart = fridayStart;
		this.fridayEnd = fridayEnd;
		this.saturdayStart = saturdayStart;
		this.saturdayEnd = saturdayEnd;
		this.sundayStart = sundayStart;
		this.sundayEnd = sundayEnd;
		this.email = email;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.locations = locations;
		this.licenses = licenses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "userId", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "isProvider", nullable = false)
	public boolean isIsProvider() {
		return this.isProvider;
	}

	public void setIsProvider(boolean isProvider) {
		this.isProvider = isProvider;
	}

	@Column(name = "firstName", nullable = false, length = 20)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 20)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "suffix", length = 5)
	public String getSuffix() {
		return this.suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	@Column(name = "address", nullable = false, length = 64)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city", nullable = false, length = 64)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "zipcode", nullable = false, length = 5)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "phoneNumber", nullable = false, length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "phoneOk", nullable = false)
	public boolean isPhoneOk() {
		return this.phoneOk;
	}

	public void setPhoneOk(boolean phoneOk) {
		this.phoneOk = phoneOk;
	}

	@Column(name = "textOk", nullable = false)
	public boolean isTextOk() {
		return this.textOk;
	}

	public void setTextOk(boolean textOk) {
		this.textOk = textOk;
	}

	@Column(name = "emailOk", nullable = false)
	public boolean isEmailOk() {
		return this.emailOk;
	}

	public void setEmailOk(boolean emailOk) {
		this.emailOk = emailOk;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "mondayStart", length = 8)
	public Date getMondayStart() {
		return this.mondayStart;
	}

	public void setMondayStart(Date mondayStart) {
		this.mondayStart = mondayStart;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "mondayEnd", length = 8)
	public Date getMondayEnd() {
		return this.mondayEnd;
	}

	public void setMondayEnd(Date mondayEnd) {
		this.mondayEnd = mondayEnd;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "tuesdayStart", length = 8)
	public Date getTuesdayStart() {
		return this.tuesdayStart;
	}

	public void setTuesdayStart(Date tuesdayStart) {
		this.tuesdayStart = tuesdayStart;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "tuesdayEnd", length = 8)
	public Date getTuesdayEnd() {
		return this.tuesdayEnd;
	}

	public void setTuesdayEnd(Date tuesdayEnd) {
		this.tuesdayEnd = tuesdayEnd;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "wednesdayStart", length = 8)
	public Date getWednesdayStart() {
		return this.wednesdayStart;
	}

	public void setWednesdayStart(Date wednesdayStart) {
		this.wednesdayStart = wednesdayStart;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "wednesdayEnd", length = 8)
	public Date getWednesdayEnd() {
		return this.wednesdayEnd;
	}

	public void setWednesdayEnd(Date wednesdayEnd) {
		this.wednesdayEnd = wednesdayEnd;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "thursdayStart", length = 8)
	public Date getThursdayStart() {
		return this.thursdayStart;
	}

	public void setThursdayStart(Date thursdayStart) {
		this.thursdayStart = thursdayStart;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "thursdayEnd", length = 8)
	public Date getThursdayEnd() {
		return this.thursdayEnd;
	}

	public void setThursdayEnd(Date thursdayEnd) {
		this.thursdayEnd = thursdayEnd;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "fridayStart", length = 8)
	public Date getFridayStart() {
		return this.fridayStart;
	}

	public void setFridayStart(Date fridayStart) {
		this.fridayStart = fridayStart;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "fridayEnd", length = 8)
	public Date getFridayEnd() {
		return this.fridayEnd;
	}

	public void setFridayEnd(Date fridayEnd) {
		this.fridayEnd = fridayEnd;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "saturdayStart", length = 8)
	public Date getSaturdayStart() {
		return this.saturdayStart;
	}

	public void setSaturdayStart(Date saturdayStart) {
		this.saturdayStart = saturdayStart;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "saturdayEnd", length = 8)
	public Date getSaturdayEnd() {
		return this.saturdayEnd;
	}

	public void setSaturdayEnd(Date saturdayEnd) {
		this.saturdayEnd = saturdayEnd;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "sundayStart", length = 8)
	public Date getSundayStart() {
		return this.sundayStart;
	}

	public void setSundayStart(Date sundayStart) {
		this.sundayStart = sundayStart;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "sundayEnd", length = 8)
	public Date getSundayEnd() {
		return this.sundayEnd;
	}

	public void setSundayEnd(Date sundayEnd) {
		this.sundayEnd = sundayEnd;
	}

	@Column(name = "email", unique = true, nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Location> getLocations() {
		return this.locations;
	}

	public void setLocations(Set<Location> locations) {
		this.locations = locations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<License> getLicenses() {
		return this.licenses;
	}

	public void setLicenses(Set<License> licenses) {
		this.licenses = licenses;
	}

}
