---
# Installs software and adds repos for apt, (ubuntu).
- name: Add all of the required repositories.
  tags: repo
  apt_repository: repo="{{ item }}" 
  with_items: apt_repos
  when: apt_repos is defined

- name: run apt-get update
  tags: cache-update
  apt: update_cache=yes

- name: Install required software.
  tags: install
  apt: 
    pkg: "{{ item }}"
    state: latest
    update_cache: no
  with_items: apt_packages
  when: apt_packages is defined
