---
- hosts: spring-tomcat-servers
  remote_user: root
  vars: 
    new_user: tomcat
    http_port: 80

    # ansible-mysql variables
    mysql_root_password: rootpassword
    mysql_enabled_on_startup: yes
    
    mysql_databases: 
        - name: help_me_db
          encoding: latin1
          collation: latin1_general_ci
          
    mysql_users: 
      - name: helper
        host: "%"
        password: helperpassword
        priv: "help_me_db.*:ALL"

    mysql_packages:
        - mysql-server
        - mysql-client

    # Ansible maven variables.
    maven_major: 3
    maven_release: 3.3.9
    
    # Git stuff
    git_branch: master
    git_url: git@github.com:sharonp1130/iHeartMattJTriviski.git
    git_dest_dir: "/home/{{ new_user }}/help_me"

  roles:
    - { role: add_user }
    - { role: ansible-java-oracle }
    - { role: ansible-mysql }
    - { role: ansible-maven}
    - { role: git_bootstrap, tags: [bootstrap] }
    - { role: git, tags: [git, install] }
