---
# This playbook runs on Ubuntu 14.4 systems only.  Will install 
# all of the necessary packages for a help me rest server.
- hosts: spring-tomcat-servers
  remote_user: root
  
  pre_tasks:
    # Add all the required repos and keys to install mariaDB 10.
    - name: Install software properties common
      apt: name=software-properties-common
      tags: pre
      
    - name: Add apt key
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0xcbcb082a1bb943db state=present
      tags: pre
      
    - name: Add repository for Ubuntu 14.4
      apt_repository: repo='deb http://ftp.kaist.ac.kr/mariadb/repo/10.0/ubuntu trusty main'
      register: results
      tags: pre
      
    - name: Update apt-cache if the repo was added.
      apt: update_cache=yes
      when: results.changed
      tags: pre
  
  vars: 
    http_port: 80
    db_name: help_me_db
    
    mysql_root_password: rootpassword
    
    # This will force change the password.
    mysql_root_password_update: yes

    mysql_enabled_on_startup: yes
    
    mysql_databases: 
        - name: "{{ db_name }}"
          encoding: latin1
          collation: latin1_general_ci
          
    mysql_users: 
      - name: helper
        host: "%"
        password: helperpassword
        priv: "{{ db_name }}.*:ALL"
        
    # I guess this is the default so things won't start
    # if this doesn't match what is configured in mysql.  
    # This goes to the /etc/mysql/my.cnf file so if this 
    # needs to change will have to figure that out some other 
    # time
    mysql_innodb_log_file_size: 5M
    
    # Mariadb for ubuntu
    mysql_packages:
      - mariadb-client
      - mariadb-server
      - python-mysqldb

    # Tomcat variables
    tomcat_ubuntu_user_install: yes
    tomcat_ubuntu_mysql_jbdc_install: yes
    
  roles:
    - { role: ansible-java-oracle, tags: [install, java] }
    - { role: ansible-mysql, tags: [install, mysql]}
    - { role: ansible-tomcat8, tags: [install, tomcat]}
