---
- hosts: spring-tomcat-servers
  remote_user: root
  vars: 
    new_user: tomcat
    http_port: 80

    # ansible-mysql variables
    mysql_root_password: rootpassword
    mysql_enabled_on_startup: yes
    
    mysql_databases: 
        - name: help_me_db
          encoding: latin1
          collation: latin1_general_ci
          
    mysql_users: 
      - name: helper
        host: "%"
        password: helperpassword
        priv: "help_me_db.*:ALL"

    mysql_packages:
        - mysql-server
        - mysql-client

    # Ansible maven variables.
    maven_major: 3
    maven_release: 3.3.9
    
    # Git stuff
    git_branch: master
    git_url: git@github.com:sharonp1130/iHeartMattJTriviski.git
    git_dest_dir: "/home/{{ new_user }}/help_me"

    # Tomcat variables
    tomcat_ubuntu_user_install: yes
    tomcat_ubuntu_mysql_jbdc_install: yes

  tasks:
    - name: Build the project and deploy the war file to tomcat.


  roles:
    - { role: add_user, tags: [user]}
    - { role: ansible-java-oracle, tags: [install, java] }
    - { role: ansible-mysql, tags: [install, mysql]}
    - { role: ansible-maven, tags: [install, maven]}
    - { role: ansible-tomcat8, tags: [install, tomcat]}
    - { role: git_bootstrap, tags: [bootstrap] }
    - { role: git, tags: [install, git] }
