<?php

namespace HelpMe\ServiceProviderBundle\Entity;

/**
 * ProviderInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
