-- MySQL Script generated by MySQL Workbench
-- Fri Aug 14 22:09:06 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema apollo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `apollo` ;

-- -----------------------------------------------------
-- Schema apollo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apollo` DEFAULT CHARACTER SET latin1 ;
USE `apollo` ;

-- -----------------------------------------------------
-- Table `apollo`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apollo`.`user` (
  `userId` INT(32) NOT NULL AUTO_INCREMENT,
  `isProvider` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Set is provider else not provider.',
  `userName` VARCHAR(32) NOT NULL,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `suffix` VARCHAR(5) NULL DEFAULT NULL,
  `address` VARCHAR(64) NOT NULL,
  `phoneNumber` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `lastUpdate` DATETIME NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `typeId_UNIQUE` (`userId` ASC),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `apollo`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apollo`.`service` (
  `serviceId` INT(32) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`serviceId`),
  UNIQUE INDEX `description_UNIQUE` (`description` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `apollo`.`license`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apollo`.`license` (
  `licenseId` INT(32) NOT NULL,
  `licenseNumber` VARCHAR(32) NOT NULL,
  `service` INT(32) NOT NULL COMMENT 'Primary key into the service type table.',
  `user` INT(32) NOT NULL COMMENT 'Primary key into the user table.',
  `lastUpdate` DATETIME NOT NULL COMMENT 'Made diatomite since hibernate will take care of this.',
  PRIMARY KEY (`licenseId`),
  UNIQUE INDEX `licenseId_UNIQUE` (`licenseId` ASC),
  UNIQUE INDEX `licenseNumber_UNIQUE` (`licenseNumber` ASC),
  INDEX `license_servicetype_fk_idx` (`service` ASC),
  INDEX `license_uid_fk_idx` (`user` ASC),
  CONSTRAINT `license_uid_fk`
    FOREIGN KEY (`user`)
    REFERENCES `apollo`.`user` (`userId`)
    ON UPDATE CASCADE,
  CONSTRAINT `license_serv_fk`
    FOREIGN KEY (`service`)
    REFERENCES `apollo`.`service` (`serviceId`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `apollo`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apollo`.`location` (
  `locationId` INT(32) NOT NULL,
  `user` INT(32) NOT NULL COMMENT 'Primary key into the user table.',
  `longitude` DOUBLE NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `lastUpdate` DATETIME NOT NULL,
  PRIMARY KEY (`locationId`),
  UNIQUE INDEX `locationId_UNIQUE` (`locationId` ASC),
  INDEX `location_fk_idx` (`user` ASC),
  CONSTRAINT `location_fk`
    FOREIGN KEY (`user`)
    REFERENCES `apollo`.`user` (`userId`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `apollo`.`userSettings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apollo`.`userSettings` (
  `settingsId` INT(32) NOT NULL AUTO_INCREMENT,
  `user` INT(32) NOT NULL COMMENT 'Foreign key into user table.',
  `phoneOk` TINYINT(1) NOT NULL DEFAULT '1',
  `textOk` TINYINT(1) NOT NULL DEFAULT '1',
  `emailOk` TINYINT(1) NOT NULL DEFAULT '1',
  `mondayStart` DATETIME NULL DEFAULT NULL,
  `mondayEnd` DATETIME NULL DEFAULT NULL,
  `tuesdayStart` DATETIME NULL DEFAULT NULL,
  `tuesdayEnd` DATETIME NULL DEFAULT NULL,
  `wednesdayStart` DATETIME NULL DEFAULT NULL,
  `wednesdayEnd` DATETIME NULL DEFAULT NULL,
  `thursdayStart` DATETIME NULL DEFAULT NULL,
  `thursdayEnd` DATETIME NULL DEFAULT NULL,
  `fridayStart` DATETIME NULL DEFAULT NULL,
  `fridayEnd` DATETIME NULL DEFAULT NULL,
  `saturdayStart` DATETIME NULL DEFAULT NULL,
  `saturdayEnd` DATETIME NULL DEFAULT NULL,
  `sundayStart` DATETIME NULL DEFAULT NULL,
  `sundayEnd` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`settingsId`),
  INDEX `nhh_idx` (`user` ASC),
  CONSTRAINT `usersettings_fk`
    FOREIGN KEY (`user`)
    REFERENCES `apollo`.`user` (`userId`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
