-- MySQL Script generated by MySQL Workbench
-- Sun Aug  2 22:54:32 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema apollo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `apollo` ;

-- -----------------------------------------------------
-- Schema apollo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apollo` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `apollo` ;

-- -----------------------------------------------------
-- Table `apollo`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `apollo`.`user` (
  `userId` INT(32) NOT NULL AUTO_INCREMENT,
  `isProvider` BIT(1) NOT NULL DEFAULT b'0' COMMENT 'Set is provider else not provider.',
  `userName` VARCHAR(32) NOT NULL,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `suffix` VARCHAR(5) NULL DEFAULT NULL,
  `address` VARCHAR(64) NOT NULL,
  `phoneNumber` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `lastUpdate` DATETIME NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `typeId_UNIQUE` (`userId` ASC),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `apollo`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`service` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `apollo`.`service` (
  `serviceId` INT(32) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`serviceId`),
  UNIQUE INDEX `description_UNIQUE` (`description` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `apollo`.`license`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`license` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `apollo`.`license` (
  `licenseId` INT(32) NOT NULL,
  `licenseNumber` VARCHAR(32) NOT NULL,
  `service` INT(32) NOT NULL COMMENT 'Primary key into the service type table.',
  `user` INT(32) NOT NULL COMMENT 'Primary key into the user table.',
  `lastUpdate` DATETIME NOT NULL COMMENT 'Made diatomite since hibernate will take care of this.',
  PRIMARY KEY (`licenseId`),
  UNIQUE INDEX `licenseId_UNIQUE` (`licenseId` ASC),
  UNIQUE INDEX `licenseNumber_UNIQUE` (`licenseNumber` ASC),
  INDEX `license_servicetype_fk_idx` (`service` ASC),
  INDEX `license_uid_fk_idx` (`user` ASC),
  CONSTRAINT `license_uid_fk`
    FOREIGN KEY (`user`)
    REFERENCES `apollo`.`user` (`userId`)
    ON UPDATE CASCADE,
  CONSTRAINT `license_serv_fk`
    FOREIGN KEY (`service`)
    REFERENCES `apollo`.`service` (`serviceId`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `apollo`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`location` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `apollo`.`location` (
  `locationId` INT(32) NOT NULL,
  `user` INT(32) NOT NULL COMMENT 'Primary key into the user table.',
  `longitude` DOUBLE NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `lastUpdate` DATETIME NOT NULL,
  PRIMARY KEY (`locationId`),
  UNIQUE INDEX `locationId_UNIQUE` (`locationId` ASC),
  INDEX `location_fk_idx` (`user` ASC),
  CONSTRAINT `location_fk`
    FOREIGN KEY (`user`)
    REFERENCES `apollo`.`user` (`userId`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `apollo`.`userSettings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`userSettings` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `apollo`.`userSettings` (
  `settingsId` INT(11) NOT NULL AUTO_INCREMENT,
  `user` INT(32) NOT NULL COMMENT 'Foreign key into user table.',
  `phoneOk` BIT(1) NOT NULL DEFAULT b'1',
  `textOk` BIT(1) NOT NULL DEFAULT b'0',
  `emailOk` BIT(1) NOT NULL DEFAULT b'0',
  `mondayStart` INT(32) NULL DEFAULT NULL,
  `mondayEnd` INT(32) NULL DEFAULT NULL,
  `tuesdayStart` INT(32) NULL DEFAULT NULL,
  `tuesdayEnd` INT(32) NULL DEFAULT NULL,
  `wednesdayStart` INT(32) NULL DEFAULT NULL,
  `wednesdayEnd` INT(32) NULL DEFAULT NULL,
  `thursdayStart` INT(32) NULL DEFAULT NULL,
  `thursdayEnd` INT(32) NULL DEFAULT NULL,
  `fridayStart` INT(32) NULL DEFAULT NULL,
  `fridayEnd` INT(32) NULL DEFAULT NULL,
  `saturdayStart` INT(32) NULL DEFAULT NULL,
  `saturdayEnd` INT(32) NULL DEFAULT NULL,
  PRIMARY KEY (`settingsId`),
  INDEX `nhh_idx` (`user` ASC),
  CONSTRAINT `usersettings_fk`
    FOREIGN KEY (`user`)
    REFERENCES `apollo`.`user` (`userId`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `apollo`.`service`
-- -----------------------------------------------------
START TRANSACTION;
USE `apollo`;
INSERT INTO `apollo`.`service` (`serviceId`, `description`) VALUES (1, 'electrical');
INSERT INTO `apollo`.`service` (`serviceId`, `description`) VALUES (2, 'massage');
INSERT INTO `apollo`.`service` (`serviceId`, `description`) VALUES (3, 'plumbing');
INSERT INTO `apollo`.`service` (`serviceId`, `description`) VALUES (4, 'roofing');
INSERT INTO `apollo`.`service` (`serviceId`, `description`) VALUES (5, 'tickling');

COMMIT;

